M48
; DRILL file {KiCad 6.0.8-f2edbf62ab~116~ubuntu22.04.1} date Sun 30 Oct 2022 10:41:42 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-30T22:41:42-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8-f2edbf62ab~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X4.795Y-3.7327
X5.925Y-3.7327
T2
X4.8101Y-2.74
X4.8101Y-3.18
X5.9925Y-2.84
T0
M30
